apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- ../templates

# - patches/manager_webhook_patch_certmanager.yaml # [CERTMANAGER] To enable cert-manager, you need to uncomment all the sections with [CERTMANAGER]
patchesStrategicMerge:
- patches/manager_webhook_patch_spire.yaml
- patches/manager_resource_templates_patch.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- files:
  - resource_requirements/stateless-lb
  - resource_requirements/nsc
  - resource_requirements/frontend
  - resource_requirements/nse-vlan
  - resource_requirements/proxy
  - resource_requirements/nsp
  - resource_requirements/ipam
  name: resource-templates
  options:
    disableNameSuffixHash: true

images:
- name: operator
  newName: registry.nordix.org/cloud-native/meridio/operator
  newTag: latest
