apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: $(SERVICE_NAMESPACE)
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      volumes:
      - name: templates-volume
        configMap:
          name: deployment-templates
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        env:
          - name: RESOURCE_NAME_PREFIX
            value: ""
          - name: NSM_REGISTRY_SERVICE
            value: "nsm-registry-svc.nsm:5002"
          - name: LOG_LEVEL
            value: "debug"
          - name: IMAGE_PULL_SECRET
            value: "" # multiple secrets supported, use "," as the delimiter
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /deployment
          name: templates-volume
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
