apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fes-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fes-role
subjects:
- kind: ServiceAccount
  name: fes
  namespace: system 
