resources:
- manifests.yaml

configurations:
- kustomizeconfig.yaml

# add namespace selector to the webhooks to restrict the working scope
# This takes the label "kubernetes.io/metadata.name" of a namespace, which added in Kuberntes 1.21[beta feature]
# This block should be commented if using a Kubernetes version earlier than that
patches:
# patches for mutating webhooks
- target:
   group: admissionregistration.k8s.io
   version: v1
   kind: MutatingWebhookConfiguration
   name: operator-mutating-webhook-configuration
  path: patches/mwebhook_namespace_selector_patch.yaml
