# Source: meridio/templates/lb-fe.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-fe
  labels:
    app: lb-fe
spec:
  selector:
    matchLabels:
      app: lb-fe
  replicas: 2
  template:
    metadata:
      labels:
        spiffe.io/spiffe-id: "true"
        app: lb-fe
    spec:
      serviceAccountName: # to be filled by operator
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - "lb-fe"
              topologyKey: kubernetes.io/hostname
      initContainers:
        - name: sysctl-init
          image: registry.nordix.org/cloud-native/meridio/busybox:1.29
          securityContext:
            privileged: true
          command: ["/bin/sh"]
          args: # to be filled by operator according to trench
      containers:
        - name: load-balancer
          image: # to be filled by operator
          imagePullPolicy: # Kubernetes default according to image tag
          readinessProbe: # will be overwritten by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:8000
                - -connect-timeout=100ms
                - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          livenessProbe: # will be overwritten by operator if not specified
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr=:8000
                - -connect-timeout=100ms
                - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_SERVICE_NAME
              value: # to be filled by operator
            - name: NSM_CONDUIT_NAME
              value: # to be filled by operator
            - name: NSM_TRENCH_NAME
              value: # to be filled by operator
            - name: NSM_NSP_SERVICE
              value: # to be filled by operator
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
          securityContext:
            privileged: true
        - name: nsc
          image: # to be filled by operator if not specified
          imagePullPolicy: # Kubernetes default according to image tag
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSM_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSM_NETWORK_SERVICES
              value: # to be filled by operator
            - name: NSM_DIAL_TIMEOUT
              value: "30s"
            - name: NSM_REQUEST_TIMEOUT
              value: "300s"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: true
        - name: fe
          image: # to be filled by operator
          imagePullPolicy: # Kubernetes default according to image tag
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NFE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NFE_LOG_BIRD
              value: "true"
            - name: NFE_ECMP
              value: "true"
            - name: NFE_NSP_SERVICE
              value: # to be filled by operator
            - name: NFE_CONFIG_MAP_NAME
              value: # to be filled by operator
            - name: NFE_TRENCH_NAME
              value: # to be filled by operator
            - name: NFE_ATTRACTOR_NAME
              value: # to be filled by operator
          securityContext:
            privileged: true
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
