# Source: meridio/templates/nse-vlan.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-vlan
  labels:
    app: nse-vlan
spec:
  selector:
    matchLabels:
      app: nse-vlan
  template:
    metadata:
      labels:
        spiffe.io/spiffe-id: "true"
        app: nse-vlan
    spec:
      containers:
        - name: nse
          image: # to be filled by operator
          imagePullPolicy: # Kubernetes default according to image tag
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NSE_CONNECT_TO
              value: unix:///var/lib/networkservicemesh/nsm.io.sock
            - name: NSE_VLAN_BASE_IFNAME
              value: # to be filled by operator according to Attractor
            - name: NSE_VLAN_ID
              value: # to be filled by operator according to Attractor
            - name: NSE_SERVICE_NAME
              value: # to be filled by operator
            - name: NSE_CIDR_PREFIX
              value: # to be filled by operator according to Attractor
            - name: NSE_IPV6_PREFIX
              value: # to be filled by operator according to Attractor
            - name: NSE_POINT2POINT
              value: "False"
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsm-socket
              mountPath: /var/lib/networkservicemesh
              readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
        - name: nsm-socket
          hostPath:
            path: /var/lib/networkservicemesh
            type: DirectoryOrCreate
