# Source: meridio/templates/nsp.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nsp
  labels:
    app: nsp
spec:
  replicas: 1
  serviceName: nsp
  selector:
    matchLabels:
      app: nsp
  template:
    metadata:
      labels:
        spiffe.io/spiffe-id: "true"
        app: nsp
    spec:
      serviceAccountName: # to be filled by operator
      containers:
        - name: nsp
          image: # to be filled by operator
          imagePullPolicy: # Kubernetes default according to image tag
          readinessProbe: # will be overwritten by operator
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:8000
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          livenessProbe: # will be overwritten by operator
            exec:
              command:
              - /bin/grpc_health_probe
              - -addr=:8000
              - -connect-timeout=100ms
              - -rpc-timeout=150ms
            failureThreshold: 5
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///run/spire/sockets/agent.sock
            - name: NSP_PORT
              value: # to be filled by operator
            - name: NSP_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NSP_CONFIG_MAP_NAME
              value: # to be filled by operator
            - name: NSP_DATASOURCE
              value: /run/nsp/data/registry.db
          volumeMounts:
            - name: spire-agent-socket
              mountPath: /run/spire/sockets
              readOnly: true
            - name: nsp-data
              mountPath: /run/nsp/data
              readOnly: false
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/sockets
            type: Directory
  volumeClaimTemplates:
    - metadata:
        name: nsp-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi